CREATE TABLE usuario (
	ID INT NOT NULL PRIMARY KEY,
	NOME VARCHAR (200) NOT NULL ,
	DATA_NACIMENTO DATE,
	SALARIO NUMERIC,
	DIVIDA FLOAT,
	PESO DOUBLE
);

CREATE TABLE produto (
	id INT NOT NULL PRIMARY KEY,
	nome VARCHAR (100),
	ATIVO BOOLEAN NOT NULL
);

CREATE TABLE departamento (
	id INT NOT NULL PRIMARY KEY,
	nome VARCHAR (100),
	ATIVO BOOLEAN NOT NULL
);